language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

script:
    - ./vendor/bin/phpunit --configuration ./build/travis-ci.xml
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'

notifications:
  email: false
