<?php

namespace Studentbox\Backup;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-07 at 18:21:37.
 */
class DatabaseTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Database
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Database;
    }
    
    public function testSample() {
        $this->assertTrue(true);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
