<?php

namespace Studentbox\Backup;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-07 at 22:09:58.
 */
class S3Test extends \PHPUnit_Framework_TestCase {

    /**
     * @var S3
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new S3;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Studentbox\Backup\S3::test
     * @todo   Implement testTest().
     */
    public function testTest() {
        $this->assertTrue($this->object->test());
    }

}
